[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
# repo = 'osyo-manga/vim-precious'
# depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neocomplcache'
[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
[[plugins]]
repo =  'mxw/vim-jsx'
[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = 'tikhomirov/vim-glsl'
[[plugins]]
repo = 'pangloss/vim-javascript'


[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'JulesWang/css.vim'
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'isRuslan/vim-es6'

[[plugins]]
repo = 'liuchengxu/space-vim-dark'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'wavded/vim-stylus'

[[plugins]]
repo = 'vim-perl/vim-perl'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'nikvdp/ejs-syntax'

[[plugins]]
repo = 'challenger-deep-theme/vim'
name = 'challenger_deep'

[[plugins]]
repo = 'archseer/colibri.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'posva/vim-vue'

